<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-B5DT44ER" failures="0" tests="5" name="REST_Assured_Demo.REST_Assured_Demo.Day1Demo" time="10.729" errors="1" timestamp="2023-05-02T10:23:31 IST" skipped="0">
  <testcase classname="REST_Assured_Demo.REST_Assured_Demo.Day1Demo" name="createUsingJSONFile" time="0.008">
    <error message="java.io.FileNotFoundException: " type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: 
at REST_Assured_Demo.REST_Assured_Demo.Day1Demo.createUsingJSONFile(Day1Demo.java:94)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.io.FileNotFoundException: 
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileReader.<init>(FileReader.java:75)
at REST_Assured_Demo.REST_Assured_Demo.Day1Demo.createUsingJSONFile(Day1Demo.java:92)
... 28 more
]]>
    </error>
  </testcase> <!-- createUsingJSONFile -->
  <system-out/>
  <testcase classname="REST_Assured_Demo.REST_Assured_Demo.Day1Demo" name="createUserUsingORGJSON" time="9.295"/>
  <system-out/>
  <testcase classname="REST_Assured_Demo.REST_Assured_Demo.Day1Demo" name="createUserUsingPOJO" time="0.014"/>
  <system-out/>
  <testcase classname="REST_Assured_Demo.REST_Assured_Demo.Day1Demo" name="f" time="0.655"/>
  <system-out/>
  <testcase classname="REST_Assured_Demo.REST_Assured_Demo.Day1Demo" name="createUserUsingHashMap" time="0.757"/>
  <system-out/>
</testsuite> <!-- REST_Assured_Demo.REST_Assured_Demo.Day1Demo -->
